### PR TITLE
Fix Pebble compilation (#49)

### PR DESCRIPTION
**Pull request by zackp30**

### CODE REVIEW

**Comment by LB--** [comment]
It looks like your editor changed the indentation levels.

**Comment by zackp30** [comment]
Whoops, thank you! Fixing now.

**Comment by zackp30** [comment]
Fixed!

**Comment by LB--** [comment]
@zackp30 there's still a couple spaces missing from line 50 ;)

**Comment by zackp30** [comment]
Haha, thanks! Fixed. :)

**Comment by DimitriPapadopoulos** [comment]
`isdigit` expects `int`, not `unsigned char`. See #120 for a variant.

**Pull request merged**
