### PR TITLE
Copyright dates and web site updates

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Perhaps it's time we change:
```
 * Copyright (C) 2012, 2013, 2014, 2016, 2018, 2019, 2021 James McLaughlin et al.  All rights reserved.
```
to:
```
 * Copyright (C) 2012-2021 James McLaughlin et al.  All rights reserved.
```

### CODE REVIEW

**Comment by udp** [comment]
You can even just change it to “the json-parser authors” since I’m no longer the primary maintainer

**Comment by DimitriPapadopoulos** [comment]
😀 _et al._ looks good to me. But I can change it if that's what you want.

**Comment by udp** [comment]
I think there have been lots of contributors over the years now so changing it to authors makes sense 🙂

**Comment by DimitriPapadopoulos** [comment]
Done.

**Review by LB-- — APPROVED** [review]

**Pull request merged**
