### PR TITLE
Added test program for C library

### PR DESCRIPTION
**Pull request by pasqumirk**
To help people to understand better the library I wrote a simple test C program.

### CODE REVIEW

**Comment by TankMasterRL** [comment]
Excellent, why has this not been added? I know the Python test/example exist, but a pure C approach like this one would be more fitting in this case.

**Comment by pasqumirk** [comment]
I am new to Github and I do not know how to add it to udp/master.
I sent an email to udp but I received no answer (maybe it was not correct procedure)

**Comment by TankMasterRL** [comment]
Only udp can approve/add a pull request to the udp/master branch. So you
have done it right, up to udp now.
Den 2 jul 2015 10:26 skrev "Mirko Pasqualetti" <notifications@github.com>:

**Comment by udp** [comment]
Hi, thanks very much, and sorry for the late response.  I have a few niggles with this PR:

1. This is an example rather than a test, because it doesn't check anything.  I will accept this under a new examples/ directory, but not in tests/.

2. Please change the main method to return int rather than void.  void main isn't ANSI C, and if you use int main you can return instead of calling exit.

3. Please add a license header to the source file like in json.c (obviously w/ copyright altered to yourself).

**Comment by udp** [comment]
Re getting this into master - if you commit further changes to your own fork, they'll automatically be visible in this PR.  Then I can squash the commits together and merge them into master.

**Comment by udp** [comment]
Looks good!  Thanks again.

**Pull request merged**
