### PR TITLE
Fix read overflow

### PR DESCRIPTION
**Pull request by isra17**

### CODE REVIEW

**Comment by harkue** [comment]
refer issue #74

**Comment by LB--** [comment]
Thanks! I wonder though, would it not be better to just change the integer constants instead? I am sure the compiler will optimize it to the same code either way though. And, either way, would you please rebase or amend the commit to remove the whitespace changes in the diff?

**Comment by isra17** [comment]
Rebased. I personnaly prefer `<= ACTUAL_LENGTH` than `< LENGHT_PLUS_1`.

**Comment by LB--** [comment]
Thanks, and alright. Would you like your name in the AUTHORS file? I'll merge shortly.

**Comment by isra17** [comment]
I don't mind being added to `AUTHORS`, although this contribution is rather trivial. I won't change this PR, so feel free to merge as-is without the `AUTHORS` addition!

**Pull request merged**
